### ISSUE TITLE
This is really cool!

### ISSUE THREAD

**Issue by jdantonio** [SebastianEdwards/proletariat#3]
No issue, just stopping by to say I'm very excited by this gem. It is very cool. I use RabbitMQ heavily at work and my dissatisfaction with the available Ruby concurrency tools lead me to create the concurrent-ruby gem in the first place. I chose the EventMachine-based AMQP gem at work because I needed something mature at the time. That gem has served us well for two years, but I really dislike reactor-based programming. Had your gem been around back then it may have been the core of the application I was architecting. So it's pretty amazing for me to see you using my gem to build this.

Please let me know if there is anything I can do to facilitate your work. It's pretty awesome and I hope our gem has been beneficial.

**Comment by SebastianEdwards** [comment]
Thanks for the encouragement! This gem is fairly new and far from battle-tested. As far as I know; no one else is using proletariat at this stage. That said, I'm finding excellent performance and stability characteristics in my own system - largely owing to the great concurrency code lying underneath. :+1: 

Looking at the code today, I really should have done a better job of isolating the concurrency from the business logic. Unfortunately, this code has paid the price for being the first multi-threaded Ruby code I've written. I'm looking forward to seeing some other codebases using some of these concurrency primitives (especially Actors) to see how they architect things and borrowing the best ideas.

While you are here, I must say: concurrent-ruby is such a boon to the Ruby community. Multi-threaded Ruby code is now accessible to a whole new audience of developers (myself included). I really can't being to imagine approaching a problem like this now without it. Thanks so much for all your great work on the gem!
